kind: Pod

apiVersion: v1

metadata:
  name: hello-pod
  labels:
    hello: my-first-pod

spec:
  containers:
    - name: hello-container
      image: nginx
      ports:
        - containerPort: 80
          hostPort: 8080

# kubectl create -f hello-pod.yaml